[workspace]
members = [
    "node",
    "runtime",
    "modules/primitives",
    "modules/governance",
    "modules/template",
    "modules/opus",
    "modules/interaction",
    "modules/curated-group",
    "modules/tcx"
]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
