[workspace]
members = [
    "node",
    "runtime",
    "modules/template",
    "modules/primitives",
    "modules/content-node"
]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
